# Generated by Django 4.2.11 on 2024-04-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imgpath', models.TextField(blank=True, db_column='imgPath', null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('mpaarating', models.TextField(blank=True, db_column='mpaaRating', null=True)),
                ('userrating', models.TextField(blank=True, db_column='userRating', null=True)),
            ],
        ),
    ]
